### ISSUE TITLE
Prefix all SC interface methods

### ISSUE THREAD

**Issue by damip** [massalabs/massa-standards#107]
## Description

Currently, a given SC cannot implement both the FT and NFT standard SC interfaces because both expect the same  exported function name `transfer` and therefore collide.

## TODO

We should make sure that standard function names never collide between SC interface standards.

To do this, we could simply name the standards (eg. `NFT1`) and prefix all the exported functions with that name: `NFT1_transfer`, `FT1_transfer` to remove any ambiguity, even between different installments of the same category of interfaces (eg. different versions of the fungible token interface).

Port this to existing standards:
* [x] https://github.com/massalabs/massa-standards/issues/108
* [x] https://github.com/massalabs/massa-standards/issues/109
* [x] https://github.com/massalabs/massa-standards/issues/110

**Comment by damip** [comment]
@gregLibert @qdrn @AurelienFT what do you think ?

**Comment by AurelienFT** [comment]
I understand the fact that you need different name but i'm not a fan of the proposal it seems very close to what Ethereum did and I don't like the way they are doing it.

When, for example, people (non-devs) talk about ERC20 they don't even know that is a standard etc they just think ERC20 == cryptocurrency on ETH.

Personally I think we could make `FT1_transfer`/`FT2_transfer`/`NFT1_transfer` so that people (non-devs) will talk about FT (which means something) instead of ERC20 (or MRC20).

I think we can enough possibilities with the letters in the prefix as there is enough for currency IRL (USD, EUR,...) or cryptocurrency (USDT, USDC,...)  and it's more understandable.

**Comment by gregLibert** [comment]
> Currently, a given SC cannot implement both the FT and NFT standard SC interfaces because both expect the same exported function name `transfer` and therefore collide.

Shouldn't we use an (N)FT standard for that ? The famous ERC-1155 ?

**Comment by AurelienFT** [comment]
> Shouldn't we use an (N)FT standard for that ? The famous ERC-1155 ?

I think @damip took a particular case but the issue concern a more larger problem which is "we can't have two method with same name in our standard"

**Comment by AurelienFT** [comment]
Or with : https://github.com/massalabs/massa-standards/issues/107#issuecomment-1649420320 :)

**Comment by gregLibert** [comment]
> > Shouldn't we use an (N)FT standard for that ? The famous ERC-1155 ?
> 
> I think @damip took a particular case but the issue concern a more larger problem which is "we can't have two method with same name in our standard"

But is it a real life problem or a theoritical one ?

**Comment by AurelienFT** [comment]
> But is it a real life problem or a theoritical one ?

Depends if we follow ethereum and only one standard is used at a time and so you have to redefine everything or if you could have a standard that just offer a different way of transfering for example and you don't want to redefine all the rest i your standard

**Comment by damip** [comment]
I agree that the prefix can be chosen in a clearer way (eg. `FT2_` instead of `MRC3_") but when the number of standards increases, this will become a requirement to avoid worrying about not having identically named functions (eg. tranfer) between a new standard being added and all the other standards that might be used simultaneously.

Note that some standards such as this one: https://github.com/massalabs/massa-standards/issues/106 might be implemented my many SCs, alongside other standards.

**Comment by damip** [comment]
Updated the issue description given the decided format

**Comment by peterjah** [comment]
why not just this?
```
import { transfer as NFTTransfer } from "NFT';
import { transfer as FTTransfer } from "FT';
```
