### ISSUE TITLE
Massa Wallet File Standard

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-standards#15]
## Context

*Describe / explain why we should do this: motivations, context or other info.*

Several software programs needs and use wallet for massa: 
- massa node
- thyra
- web3

We need to define how the wallet.dat is created so that any current and future application can interact with wallet files.

Related to: https://github.com/massalabs/massa-standards/issues/13

Issues for implementing this standard:
- [ ] https://github.com/massalabs/massa-sc-toolkit/issues/20
- [ ] https://github.com/massalabs/massa/issues/3444
- [ ] https://github.com/massalabs/thyra-plugin-wallet/issues/29

## How to

*List the step-by-step to get it do if needed (optional)*

Currently, massa-node generate a `wallet.dat`.

Thyra used to generate a file for the wallet, now you import a wallet with a private key.

Massa-web3: you provide a private key

Massa Smart-contract tooling: the wallet is represented as a private key in a `.env` file.

## Technical details

*For Dev: give the technical insights so anyone in the team can tackle the tasks*

Determine:
- if the way massa-node generate the wallet.dat file follow the security best practices
- if it's a good idea to standardize this way

Steps:
- describe, in that repo, in a .md file how the wallet.dat file is generated: encryption algorithm.
- create an issue in Thyra repo to make Thyra implement this standard
- create issue in other repositories to implement that standard.

**Comment by damip** [comment]
This will also need updates:
* online explorers (ours + community's)
* rust client (sync with core team)
* thyra wallet plugin
* community browser plugin wallets

**Comment by BatiGencho** [comment]
Hereby, after having looked at Thyra and Massa Client, I would suggest the following format below. Since we dont really have menmonic wallets , hierarchical wallets etc. we could simply stick to what we have already done in Thyra and Massa-Client and what I believe wraps up our needs in the best possible ways.


```json

[
    {
      wallet_type: "stringified_wallet_type1",
      name: "MyDemoWallet",
      accounts: [
         {
           PrivateKey: 0x0...,
           PublicKey: 0x0...,
         }
      ]
    },
    {
      wallet_type: "stringified_wallet_type2",
      name: "MyTradingWallet",
      accounts: [
         {
           PrivateKey: 0x0...,
           PublicKey: 0x0...,
         }
      ]
    }
]


```


The idea here is that we have a .json file that contains a list of Wallet blocks each of which has a wallet_type (explained further down), a name, and accounts - an array of private-public key pairs.


To illustrate the idea, here is a pseudo-rust implementation of a so-called Vault, which contains n x Wallets.

First, similarly to Thyra and Massa-rs, we can have json serializable and deserializable structures for our KeyPairs and Wallet as shown below. I have also added a walletType which is meant to be a complex type containing the version and the uuid of the given wallet. We could have wallets with equal names, but different types e.g. a Thyra wallet of v1.0 and maybe another unique identifier e.g. Uuid. Based on the wallet type and its version we would know how to deserialize and serialize the rest of the structure. 

```rust
    struct UniqueWalletVersion((String, Uuid))

 #[derive(Serialize, Deserialize)]
    enum EWalletType {
        Thyra(UniqueWalletVersion),
        BrowserPlugin((UniqueWalletVersion),
        Bearby(UniqueWalletVersion)
    }

    #[derive(Serialize, Deserialize)]
    struct KyPair {
        PrivateKey: PrivateKey,
        PublicKey:  PublicKey,
        Salt:       Option<Salt>,
        Nonce:      Option<Nonce>,
    }

 #[derive(Serialize, Deserialize)]
    struct Wallet {
        walletType: EWalletType,
        name: String,
        accounts: HashMap<Address, Keypair>
    }
```

The Vault implementation could contain these methods:

```rust

 struct Vault {
        wallets: Vec<Wallet>
     }

     impl Vault {

    // ---------------- initializers/savers/loaders ------------------ //
       pub fn new() -> Self {
           Self {wallets: vec![]}
       }


     fn load_vault(from_path: Path, password: String) -> Vault {
           // loads the .dat file from path
           // decrypts the binary contents
           // initializes a Vault
     }


    fn save_vault(&self, to_path: Path, password: String) -> Result<(), WalletError> {
      // conversts the self.wallets to json
      // aes encrypts the json bytes
      // saves output to a file.dat
    }


    // ---------------- setters ------------------ //
    fn empty_vault(&mut self) {
      // removes all wallets from vault
    }

    fn delete_wallet_or_addresses(&mut self, filter: &SearchFilter) -> Result<(), WalletError> {
        // finds the wallet by the filter and deletes all or some of its address-keypairs. The filter controls the deletion query
     }

     fn add_keypair_to_wallet(&mut self, filter: &SearchFilter, keypair: Vec<KeyPair>) -> Result<(), WalletError> { 
       // adds key-pair values to the vault as per search filter
     }



    // ---------------- getters ------------------ //
     fn get_pub_key(&self, filter: &SearchFilter) -> Option<&PublicKey>

     fn get_pub_keys(&self, filter: &SearchFilter) -> Vec<PubKey>>;

     fn get_addresses(&self, filter: &SearchFilter) -> Vec<Address>;

     fn get_keypairs(&self, filter: &SearchFilter) -> Vec<&KeyPair>;




     // ---------------- user methods ------------------ //
     fn sign_message(&self, filter: &SearchFilter, msg: Vec<u8>) -> Option<PubkeySig> {}

     fn get_all_wallets(&self) -> &[&Wallet]

     fn print(&self) -> String {
       // prints the wallet using a formatted string
     }

}

```

A search filter could be something like:

```rust
    struct SearchFilter {
        type: Option<EWalletType>,
        name: Option<&str>,
        address: Option<Vec<Address>>
    }
```

In the json file, the wallet_type could be something like : `serialized(EWalletType::Thyra(("v1.0.1", Uuid::parse_str("67e55044-10b1-426f-9247-bb680e5fe0c8"))),` , basically a serialized version of the wallet type, version and maybe some further indicators to create a finer level of versioning.

I believe we could achieve something similar with all there - rust, go and typescript. As AES algorithm we could stick to AES GCM

**Comment by BatiGencho** [comment]
@damip

**Comment by Thykof** [comment]
@BatiGencho in your json template, private key is in plain text, but if I understand well it will be encrypted with AES GCM, so what would be the structure of the final wallet.dat file?

**Comment by BatiGencho** [comment]
@Thykof The .dat file is never saved as a json file. The data file is a binary data file. It is build in that way:
```
        let serialized = Json.stringify(wallets);
        let encrypted_content = encrypt(password, serialized.bytes())
        fs:write(wallet_path, encrypted_content)
```
As you can see we are json-ifying the vault state, encrypting it with a pwd and then writing the bytes to a file. Theoretically we could have a method to also print the json file from the vault:
```
JSON.strinfigy(wallets, null, 4)
```

if the user wants to see it, once its loaded and encrypted. The idea is to encrypt the thing as a whole and not have individual wallets encrypted as in Thyra.

**Comment by BatiGencho** [comment]
@thomas-senechal Good point. I agree ! In that case, I assume we are getting closer to:

`
    #[derive(Serialize, Deserialize)]
    struct KyPair {
        PrivateKey: PrivateKey,
        PublicKey:  PublicKey,
        Salt:       Option<Salt>,
        Nonce:      Option<Nonce>,
    }

 #[derive(Serialize, Deserialize)]
    struct Wallet {
        version: String,
        name: String,
        accounts: HashMap<Address, Keypair>
    }

`

**Comment by BatiGencho** [comment]
@damip  ?

**Comment by bilboquet** [comment]
Hi

On core side we have [#3444](https://github.com/massalabs/massa/issues/3444) to track this issue.
I've asked some question there but it does not seems to get much visibility.

I'm still confused by a point: does massa-client have vocation to be a wallet manager? (At least in the short term)
I mean, the problem seems to be that (aka use-case): some users want to reuse the wallet they created with massa-client in Thyra. Fine, can't we simply export the massa-client in way that allow Thyra to import it?

Doesn't that solve the initial problem, letting time for a standard format to be defined and all roles to be clarified ?

Sorry if that looks as naive questions, I don't have the big picture yet.

**Comment by BatiGencho** [comment]
My personal opinion is that Thyra's wallet is not a standard one that blockchains would use. You dont get to encrypt specific keys only, like in Eth web3 encryption is either done as a whole, on the file level and not on individual components. The Thyra wallet system is also strange - a json file is generated for each key-value pair which we call wallet. I believe we need a vault like suggested above where we have multiple wallets (each has a version at least) and an interface to search and updated (again suggested above). I also believe web3 should be able to support that wallet standard too (meaning opening, encryption, decryptiona and using it) so that a user could also use his already existing dat file if he wants for backend services written in NodeJS.
Imagine something liek this. Express server, a dat file produced by Thyra, the server needs to sign txs e.g. We must have a method web3Client.loadWalletDatFile(...) and web3Client.saveWalletToDat(...)

To me, what needs to be done is to have Thyra redesign its wallet and massa-wallet-rs slightly extend its to allow versioning and a so-called Vault with multiple wallets.
